### ISSUE TITLE
crash because of singular matrix error

### ISSUE THREAD

**Issue by WangLicheng-HIT** [weiliangjinca/grcwa#2]
* grcwa version: 0.1.2
* Python version: 3.8
* Operating System: windows 10

### Description

I set up two pattern layers for their thickness both are 0.6, permittivity are 8 and 3.8 respectively.
And frequency is 1, lattice constants are L1 = [2,0], L2 = [0,2.]

### What I Did

```
I use the rcwa solver to get the E and H, the code as follow: 

**E,H = obj.Solve_FieldOnGrid(1,0.6)** 

and has crash as follow:

Traceback (most recent call last):
  File "D:\pycharm\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm Community Edition 2021.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/xxxx/myex1.py", line 70, in <module>
    E,H = obj.Solve_FieldOnGrid(1,0.6) # #E = [Ex,Ey,Ez], H = [Hx,Hy,Hz]
  File "D:\Anaconda\lib\site-packages\grcwa\rcwa.py", line 302, in Solve_FieldOnGrid
    fe,fh = self.Solve_FieldFourier(which_layer,z_offset)
  File "D:\Anaconda\lib\site-packages\grcwa\rcwa.py", line 268, in Solve_FieldFourier
    ai, bi = self.GetAmplitudes(which_layer,z_offset)
  File "D:\Anaconda\lib\site-packages\grcwa\rcwa.py", line 258, in GetAmplitudes
    ai, bi = SolveInterior(which_layer,self.a0,self.bN,self.q_list,self.phi_list,self.kp_list,self.thickness_list)
  File "D:\Anaconda\lib\site-packages\grcwa\rcwa.py", line 522, in SolveInterior
    S11, S12, S21, S22 = GetSMatrix(0,which_layer,q_list,phi_list,kp_list,thickness_list)
  File "D:\Anaconda\lib\site-packages\grcwa\rcwa.py", line 466, in GetSMatrix
    P1 = bd.dot(bd.diag(q_list[l]),   bd.inv(bd.dot(kp_list[l],phi_list[l])))
  File "<__array_function__ internals>", line 6, in inv
  File "D:\Anaconda\lib\site-packages\numpy\linalg\linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "D:\Anaconda\lib\site-packages\numpy\linalg\linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
python-BaseException

```

**Comment by WangLicheng-HIT** [comment]
I find the problem, if set the theta = 0, L1 = [int, 0] & L2 = [0,int], and frequency = int, then will produce crash because of singular matrix as I mentioned above

**Comment by weiliangjinca** [comment]
This type of divergence is probably due to Wood's anomalies. If you want to get an approximated result, you can try running the simulation at a frequency slightly shifted from the real axis (a finite Qabs here https://github.com/weiliangjinca/grcwa/blob/5d85c824e3f2243624c23641800f551ee935fac0/example/ex1.py#L15)
